### ISSUE TITLE
namespaces for generated tests

### ISSUE THREAD

**Issue by ronal2do** [lucasbento/create-graphql#20]
https://github.com/ronal2do/GraphQLserver/commit/5062a2805c784fb18b8ec01fc980286a98dd4de3

**Comment by sibelius** [comment]
you can use a .graphqlrc

check this out: https://github.com/lucasbento/create-graphql#configuration-file

**Comment by lucasbento** [comment]
@ronal2do: does it solve your issue?

**Comment by lucasbento** [comment]
I'm closing this, please don't hesitate to ask further questions.
