### ISSUE TITLE
`GraphQLNonNull` & `GraphQLID` not being imported on Mutation generator

### ISSUE THREAD

**Issue by lucasbento** [lucasbento/create-graphql#22]
We need to improve this: https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/mutation/index.js#L32-L51

**Comment by sibelius** [comment]
Can't we generate all that needs to be imported automatically?

**Comment by lucasbento** [comment]
@sibelius: no because some mutations might not need those types to be imported.

E.g. mutations without any required fields.

**Comment by sibelius** [comment]
that's why I said automatically 

automatically -> detect which types are being used and then import them

**Comment by lucasbento** [comment]
That's what [this](https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/mutation/index.js#L32-L51) is supposed to do but doesn't seem to be doing its job so well.

**Comment by sibelius** [comment]
add a test case
