### ISSUE TITLE
Improve Relay generation

### ISSUE THREAD

**Issue by sibelius** [lucasbento/create-graphql#25]
I think we need a flag on .graphqlrc to enable some Relay generation code tweaks

for instance a Relay GraphQL Type could have a  `globalIdField()`

Changes required on Type.js.template

```jsx
import {
  globalIdField,
} from 'graphql-relay';
import {
  NodeInterface,
} from '../interface/NodeInterface';
                                     
fields: () => ({
    id: globalIdField('Company'),
    _id: {
      type: GraphQLString,
      resolve: obj => obj._id,
    },
...

interfaces: () => [NodeInterface],                                                                                 
```

**Comment by sibelius** [comment]
maybe something like:

type: 'relay' or type: 'apollo' or type: 'raw'?

**Comment by lucasbento** [comment]
There is no need for `type: 'raw'` right now, since Apollo doesn't require any changes on server.

I thought that accepting a string may lead to errors if user provided it with a typo or something but I guess it would be better to work that way.

**Comment by lucasbento** [comment]
We are only working with Relay right now, I guess this can go on the template as well.

**Comment by sibelius** [comment]
Yep

**Comment by sibelius** [comment]
missing

`interfaces: () => [NodeInterface],`
