### ISSUE TITLE
handle mongoose ref

### ISSUE THREAD

**Issue by sibelius** [lucasbento/create-graphql#6]
For instance

```jsx
const Schema = new mongoose.Schema({
   user: {
       type: ObjectId,
       ref: 'User',
       indexed: true,
       description: 'User that created this comment',
       required: true,
  }
});
```

user field should resolve to UserType

maybe ask to create UserType as well if not created already

**Comment by sibelius** [comment]
for loaders are easy, just add 

`user: string` for Flow

and 

`this.user = data.user` on the constructor

**Comment by lucasbento** [comment]
The hardest part are the types since you would have to generate a type for each `ref`.
