### ISSUE TITLE
Refactor to improve docs

### ISSUE THREAD

**Issue by sibelius** [lucasbento/create-graphql#63]
Let's follow [react-navigation#docs](https://github.com/react-community/react-navigation/tree/master/docs) docs structure

**Comment by lucasbento** [comment]
Basically the idea of this issue is to have a `docs` folder with `.md` files that are linked on the `README.md` under a `Table of Contents` section.

cc @idkjs.

**Comment by felippepuhle** [comment]
How can we start this? Maybe we should point the topics, like a 'step by step'?

**Comment by lucasbento** [comment]
For now we can just put the sections of `README` into separated `.md` files, later on we can improve the content.

**Comment by danielfeelfine** [comment]
@felippepuhle I think we can follow the checklist below:

- [ ] Clear and improve `Readme.md`
- [ ] Create *docs* path following [react-navigation#docs](https://github.com/react-community/react-navigation/tree/master/docs)
- [ ] Move and improve existent *docs* from `Readme.md` to *docs* path
- [ ] Create `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md`

I'm working on this to keep improving the documentation of this awesome project. I will send the PR soon.
