### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jeggy** [lucasbento/create-graphql#78]
I can't install this package on Ubuntu.
Here's the output that I get: http://pastebin.com/AvCpM1Us

**Comment by felippepuhle** [comment]
`npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'`

It seems to be a permission problem, can you verify it?

**Comment by jeggy** [comment]
I know it's a permission problem, but I am running as root so I should have the right permission to it? not sure how to check that?

**Comment by jeggy** [comment]
Sorry, this isn't a create-graphql issue. just figured that I can't install any packages globally now, it worked previously, so I just gotta figure what I did...

**Comment by jeggy** [comment]
This fixed it. 
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by felippepuhle** [comment]
I changed node_modules permission manually once and some bugs like this occurred. Glad that you fixed.
