### ISSUE TITLE
Improve generated test

### ISSUE THREAD

**Issue by sibelius** [lucasbento/create-graphql#8]
right now the generated test for Type is broke

![image](https://cloud.githubusercontent.com/assets/2005841/20795717/b8ff3d4c-b7b9-11e6-87e8-a690db24f3c4.png)

**Comment by lucasbento** [comment]
@sibelius: it's broken because of the `//`, the generated tests assume that they will be changed before ran, perhaps the todo should be outside the query and nothing should run on the test initially, what do you think?

**Comment by sibelius** [comment]
this could work for now

I think the generated test should pass, I'm not sure if this is a good idea at all
