### ISSUE TITLE
add support for array field on mongoose

### ISSUE THREAD

**Issue by sibelius** [lucasbento/create-graphql#81]
```jsx
attachments: [
      {
        type: ObjectId,
        ref: 'File',
      },
    ],
```

it is not managed by create-graphql

**Comment by phra** [comment]
i think that this feature is essential for using this generator.

**Comment by JCMais** [comment]
Would we use a List or a Connection?

if the last, it would make things harder.

If the first, I have a prototype working.

cc @lucasbento

**Comment by sibelius** [comment]
It would be a GraphQLList

**Comment by lucasbento** [comment]
Added on version [v1.2.2](https://github.com/lucasbento/create-graphql/releases/tag/v1.2.2), thanks to @JCMais!
