### ISSUE TITLE
object notation should be optional

### ISSUE THREAD

**Issue by phra** [lucasbento/create-graphql#87]
hi,

when i'm trying to generate a type and a mutation from this example schema, the generator will crashes because of missing 'type' property on the field.

```js
'use strict'

var mongoose = require('mongoose')
var example= new mongoose.Schema({
	title: String
})

module.exports = mongoose.model('Example', example)
```

changing the schema in this way make the generator works again:

```js
'use strict'

var mongoose = require('mongoose')
var example= new mongoose.Schema({
	title: { type: String, }
})

module.exports = mongoose.model('Example', example)
```

**Comment by sibelius** [comment]
this is probably a problem with the way with parse mongoose schema in this function: https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/utils.js#L134

do you wanna send a PR fixing this?

**Comment by phra** [comment]
Nice!
